export { default as HeaderMain } from "./global/Header/HeaderMain.vue";
export { default as AsideMain } from "./global/AsideAdmin/AsideMain.vue";
export { default as LoadingComp } from "./global/LoadingComp.vue";
export { default as LoginComp } from "./auth/login/LoginComp.vue";
export { default as InputComp } from "./global/InputComp.vue";
export { default as ButtonComp } from "./global/ButtonComp.vue";
export { default as LogoComp } from "./global/LogoComp.vue";
export { default as RegisterComp } from "./auth/register/RegisterComp.vue";
export { default as ButtonCompBorded } from "./global/ButtonCompBorded.vue";
export { default as AsideCompProfile } from "./global/AsideAdmin/AsideCompProfile.vue";
export { default as ProfileDataComp } from "./auth/profile-responsible/ProfileDataComp.vue";
export { default as ProfileDataDriver } from "./auth/driver-responsible/ProfileDataDriver.vue";
export { default as CardAdminDriver } from "./admin/drivers/CardAdmin.vue";
export { default as TableDrivers } from "./admin/drivers/TableDrivers.vue";
export { default as TableVehicles } from "./admin/vehicles/TableVehicles.vue";
export { default as CardVehicleAdmin } from "./admin/vehicles/CardVehicleAdmin.vue";
export { default as VehicleRetrieveDataComp } from "./admin/vehicles/VehicleRetrieveDataComp.vue";
export { default as TableResponsible } from "./admin/responsibles/TableResponsible.vue"
export { default as CardResponsibleAdmin } from "./admin/responsibles/CardResponsibleAdmin.vue"
export { default as ResponsibleRetriveDataComp } from "./admin/responsibles/ResponsibleRetriveDataComp.vue"
